# Generated by Django 4.1.6 on 2023-02-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='pokemon',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='trainers',
            field=models.ManyToManyField(to='main_app.trainer'),
        ),
    ]
