# Generated by Django 4.1.6 on 2023-02-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_evolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolution',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='evolution',
            name='stage',
            field=models.CharField(choices=[('O', 'One'), ('T', 'Two'), ('N', 'None')], default='O', max_length=1),
        ),
    ]
